/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'littlegl' at '7/21/16 11:01 AM' with Gradle 2.13
 *
 * @author littlegl, @date 7/21/16 11:01 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
